//AUTOGENERATED FILE FROM png2asset
// Conversion args: snespad.png -map -noflip

#ifndef METASPRITE_snespad_H
#define METASPRITE_snespad_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define snespad_TILE_ORIGIN 0
#define snespad_TILE_W 8
#define snespad_TILE_H 8
#define snespad_WIDTH 160
#define snespad_HEIGHT 144
#define snespad_TILES_WIDTH 20
#define snespad_TILES_HEIGHT 18
#define snespad_TILE_COUNT 79
#define snespad_PALETTE_COUNT 1
#define snespad_COLORS_PER_PALETTE 4
#define snespad_TOTAL_COLORS 4
#define snespad_MAP_ATTRIBUTES 0
extern const unsigned char snespad_map[360];
#define snespad_map_attributes snespad_map

BANKREF_EXTERN(snespad)

extern const palette_color_t snespad_palettes[4];
extern const uint8_t snespad_tiles[1264];

#endif
